stages:
  preprocess:
    cmd: python3 preprocess.py
    deps:
    - preprocess.py
    - zomato_df_final_data.csv
    outs:
    - data/processed.csv

  feature_engineering:
    cmd: python3 feature_engineering.py
    deps:
    - feature_engineering.py
    - data/processed.csv
    outs:
    - data/features.csv

  train:
    cmd: python3 train.py
    deps:
    - train.py
    - zomato_df_final_data.csv
    outs:
    - models/model.pkl
    metrics:
    - results/metrics.json:
        cache: false
  evaluate:
    cmd: python3 evaluate.py
    deps:
    - evaluate.py
    - models/model.pkl
    outs:
    - results/predictions.csv
